package com.sneha.seatmgmtapp.service.impl;

import com.sneha.seatmgmtapp.service.JwtService;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import javax.crypto.SecretKey;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

/**
 * The class {@code JwtOtpSecurity} is used to handle the JWT - JSON Wen Token.
 * The class handles generation, extraction and expiry validation of tokens.
 * 
 * @author:
 * @since 1.0
 */
@Service
@Slf4j
public class JwtOtpService implements JwtService {

    // private final AuthenticationProvider authenticationProvider;

    @Value("${jwt.secret.key}")
    private String secret;

    @Value("${jwt.access.expiry.minutes}")
    private int accessExpiryMinutes;

    @Value("${jwt.refresh.expiry.days}")
    private int refreshExpiryDays;

    // JwtOtpService(AuthenticationProvider authenticationProvider) {
    // this.authenticationProvider = authenticationProvider;
    // }

    /**
     * Generates an OTP token containing the provided mobile number and ID.
     *
     * @param mobileNumber The mobile number associated with the OTP token.
     * @param id           The unique identifier associated with the OTP token.
     * @return The generated OTP token as a string.
     */
    @Override
    public String generateOtpToken(String mobileNumber, Long id, String role) {
        Map<String, Object> claims = new HashMap<>();
        claims.put("mobileNumber", mobileNumber);
        claims.put("id", id);
        claims.put("role", role);
        claims.put("type", "access");
        return createToken(claims, accessExpiryMinutes * 60 * 1000L);
    }

    /**
     * Generates a refresh token for the provided mobile number and ID.
     *
     * @param mobileNumber The mobile number associated with the refresh token.
     * @param id           The unique identifier associated with the refresh token.
     * @return The generated refresh token as a string.
     */
    @Override
    public String generateRefreshToken(String mobileNumber, Long id, String role) {
        Map<String, Object> claims = new HashMap<>();
        claims.put("mobileNumber", mobileNumber);
        claims.put("id", id);
        claims.put("role", role);
        claims.put("type", "refresh");
        return createToken(claims, refreshExpiryDays * 24 * 60 * 60 * 1000L);
    }

    /**
     * Creates a JWT token using the provided claims and the secret key.
     *
     * @param claims A map containing the claims to be included in the JWT token.
     *               The claims map should contain key-value pairs representing the
     *               desired information to be included in the token.
     *
     * @return A string representing the generated JWT token.
     *
     * @throws IllegalArgumentException If the provided claims map is null.
     */
    private String createToken(Map<String, Object> claims) {
        return createToken(claims, 0); // No expiration by default
    }

    /**
     * Creates a JWT token using the provided claims and expiration time.
     *
     * @param claims       A map containing the claims to be included in the JWT
     *                     token.
     * @param expirationMs The expiration time in milliseconds from now.
     * @return A string representing the generated JWT token.
     */
    private String createToken(Map<String, Object> claims, long expirationMs) {
        if (claims == null) {
            throw new IllegalArgumentException("Claims map cannot be null");
        }

        var builder = Jwts.builder()
                .issuedAt(new Date())
                .claims(claims)
                .signWith(getSignKey());

        if (expirationMs > 0) {
            builder.expiration(new Date(System.currentTimeMillis() + expirationMs));
        }

        return builder.compact();
    }

    /**
     * Retrieves the secret key used for signing JWT tokens.
     *
     * @return The secret key as a {@link SecretKey} instance.
     *
     * @throws IllegalArgumentException If the secret key is not properly
     *                                  configured.
     *
     * @see #secret
     */
    private SecretKey getSignKey() {
        byte[] keyBytes = Decoders.BASE64.decode(secret);
        return Keys.hmacShaKeyFor(keyBytes);
    }

    /**
     * Extracts the mobile number from the provided JWT token.
     *
     * @param token The JWT token from which to extract the mobile number.
     *              The token should be a valid OTP token generated by the
     *              {@link JwtOtpService#generateOtpToken(String, Long, String)}
     *              method.
     *
     * @return A string representing the mobile number extracted from the token.
     *         If the token is invalid or expired, this method returns null.
     *
     * @see JwtOtpService#generateOtpToken(String, Long, String)
     * @see JwtOtpService#validateOtpToken(String)
     */
    @Override
    public String extractMobileNumber(String token) {
        return extractClaim(token, claims -> claims.get("mobileNumber", String.class));
    }

    /**
     * Extracts the unique identifier (ID) from the provided JWT token.
     *
     * @param token The JWT token from which to extract the ID.
     *              The token should be a valid OTP token generated by the
     *              {@link JwtOtpService#generateOtpToken(String, Long, String)}
     *              method.
     *
     * @return A {@link Long} representing the ID extracted from the token.
     *         If the token is invalid or expired, this method returns null.
     *
     * @see JwtOtpService#generateOtpToken(String, Long, String)
     * @see JwtOtpService#validateOtpToken(String)
     */
    @Override
    public Long extractId(String token) {
        return extractClaim(token, claims -> claims.get("id", Long.class));
    }

    @Override
    public String extractRole(String token) {
        return extractClaim(token, claims -> claims.get("role", String.class));
    }

    /**
     * Checks if the provided token is a refresh token.
     *
     * @param token The JWT token to check.
     * @return true if the token is a refresh token, false otherwise.
     */
    @Override
    public boolean isRefreshToken(String token) {
        String type = extractClaim(token, claims -> claims.get("type", String.class));
        return "refresh".equals(type);
    }

    /**
     * Checks if the provided token is an access token.
     *
     * @param token The JWT token to check.
     * @return true if the token is an access token, false otherwise.
     */
    @Override
    public boolean isAccessToken(String token) {
        String type = extractClaim(token, claims -> claims.get("type", String.class));
        return "access".equals(type);
    }

    /**
     * Refreshes an access token using a valid refresh token.
     *
     * @param refreshToken The refresh token to use for generating a new access
     *                     token.
     * @return A new access token if the refresh token is valid, null otherwise.
     */
    @Override
    public String refreshAccessToken(String refreshToken) {
        if (!validateOtpToken(refreshToken) || !isRefreshToken(refreshToken)) {
            return null;
        }

        String mobileNumber = extractMobileNumber(refreshToken);
        Long id = extractId(refreshToken);
        String role = extractClaim(refreshToken, claims -> claims.get("role", String.class));

        if (mobileNumber == null || id == null) {
            return null;
        }

        return generateOtpToken(mobileNumber, id, role);
    }

    /**
     * Extracts a claim from the provided JWT token using the provided claims
     * resolver function.
     *
     * @param token          The JWT token from which to extract the claim.
     *                       The token should be a valid OTP token generated by the
     *                       {@link JwtOtpService#generateOtpToken(String, Long, String)}
     *                       method.
     *
     * @param claimsResolver A function that resolves the claim from the parsed JWT
     *                       token.
     *                       The function should take a {@link Claims} object as
     *                       input and return
     *                       the desired claim value.
     *
     * @return A value of type T representing the extracted claim from the token.
     *         If the token is invalid or expired, or if the claim cannot be
     *         resolved, this method returns null.
     *
     * @see JwtOtpService#generateOtpToken(String, Long, String)
     * @see JwtOtpService#validateOtpToken(String)
     * @see Claims
     * @see Function
     */
    @Override
    public <T> T extractClaim(String token, Function<Claims, T> claimsResolver) {
        Claims claims = extractAllClaims(token);
        return claims != null ? claimsResolver.apply(claims) : null;
    }

    /**
     * Extracts all claims from the provided JWT token.
     *
     * @param token The JWT token from which to extract the claims.
     *              The token should be a valid OTP token generated by the
     *              {@link JwtOtpService#generateOtpToken(String, Long, String)}
     *              method.
     *
     * @return A {@link Claims} object containing all the claims extracted from the
     *         token.
     *         If the token is invalid or expired, this method returns null.
     *
     * @see JwtOtpService#generateOtpToken(String, Long, String)
     */
    private Claims extractAllClaims(String token) {
        try {
            return Jwts.parser()
                    .verifyWith(getSignKey())
                    .build()
                    .parseSignedClaims(token)
                    .getPayload();
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * Validates the provided JWT token to ensure it is not expired and contains
     * valid claims.
     *
     * @param token The JWT token to be validated. Can be either access or refresh
     *              token.
     * @return {@code true} if the token is valid (not expired and contains valid
     *         claims); {@code false} otherwise.
     */
    @Override
    public boolean validateToken(String token) {
        return extractAllClaims(token) != null && !isTokenExpired(token);
    }

    /**
     * Validates the provided access token (legacy method for backward
     * compatibility).
     *
     * @param token The JWT access token to be validated.
     * @return {@code true} if the token is valid; {@code false} otherwise.
     */
    @Override
    public boolean validateOtpToken(String token) {
        return validateToken(token) && (isAccessToken(token) || isRefreshToken(token));
    }

    /**
     * Validates the provided refresh token.
     *
     * @param token The JWT refresh token to be validated.
     * @return {@code true} if the token is valid; {@code false} otherwise.
     */
    @Override
    public boolean validateRefreshToken(String token) {
        return validateToken(token) && isRefreshToken(token);
    }

    /**
     * Checks if the provided JWT token is expired.
     *
     * @param token The JWT token to be validated. The token should be a valid OTP
     *              token generated by the
     *              {@link JwtOtpService#generateOtpToken(String, Long, String)}
     *              method.
     *
     * @return {@code true} if the token is expired; {@code false} otherwise.
     *
     * @see JwtOtpService#generateOtpToken(String, Long, String)
     * @see JwtOtpService#extractClaim(String, Function)
     * @see Claims#getExpiration()
     */
    private boolean isTokenExpired(String token) {
        Date expiration = extractClaim(token, Claims::getExpiration);
        return expiration != null && expiration.before(new Date());
    }
}
